version: '3.9'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  
  backend:
    container_name: app_backend
    build:
      context: ./trainee_backend
      dockerfile: Dockerfile
      args:
        buildversion: 1
    image: backend_image:latest
    ports:
      - "5000:5000"
    env_file: ./trainee_backend/.env
    depends_on:
      - db
    networks:
      - backend

  
  db:
    container_name: app_db
    image: mysql:8.3
    ports:
      - "3307:3306"
    env_file: ./trainee_backend/.env
    volumes:
      - /mysql-data:/var/lib/mysql
    networks:
      - backend

  frontend:
    container_name: app_frontend
    build:
      context: ./trainee_frontend
      dockerfile: Dockerfile
    image: frontend_image:latest
    ports:
      - "5001:5001"
    volumes:
      - ./trainee_frontend:/app
    networks:
      - frontend